import { useContext, useEffect } from 'react'
import { TwitterContext } from '../../../context/TwitterContext'
import Image from 'next/image'
import checkMark from '../../../assets/check.png'
import { useRouter } from 'next/router'
